import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { ModalProvider } from "@/context/ModalContext";
import { LanguageProvider } from "@/context/LanguageContext";
import { CartProvider } from "@/context/CartContext";
import AuthModal from "@/components/auth/AuthModal";
import CartDrawer from "@/components/shop/CartDrawer";
import ChatWidget from "@/components/common/ChatWidget";
import PublicLayout from "@/components/layout/PublicLayout";
import { Toaster } from 'react-hot-toast'; // BİLDİRİMLER İÇİN BU GEREKLİ

const inter = Inter({ subsets: ["latin"] });

// Ayarları veritabanından çek (Tema renkleri için)
async function getSiteSettings() {
  try {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/settings`, {
      next: { revalidate: 0 }
    });
    if (!res.ok) return null;
    return res.json();
  } catch (error) {
    return null;
  }
}

export const metadata: Metadata = {
  title: "GaleryBlog",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSiteSettings();

  // Tema renklerini CSS değişkeni olarak ata
  const themeStyles = settings ? {
    '--color-background': settings.colorBackground || '#ffffff',
    '--color-text': settings.colorText || '#000000',
    '--color-primary': settings.colorPrimary || '#FFD700',
    '--color-secondary': settings.colorSecondary || '#333333',
    '--color-btn-addtocart': settings.colorButtonAddToCart || '#FFD700',
    '--color-btn-addtocart-text': settings.colorButtonAddToCartText || '#000000',
    '--color-btn-buynow': settings.colorButtonBuyNow || '#000000',
    '--color-btn-buynow-text': settings.colorButtonBuyNowText || '#ffffff',
    '--color-card-background': settings.colorCardBackground || '#343a40',
    '--color-card-text': settings.colorCardText || '#ffffff',
  } as React.CSSProperties : {};

  return (
    <html lang="tr">
      <body className={inter.className} style={themeStyles}>
        
        {/* 1. BİLDİRİM KUTUSU (Bu olmazsa bildirimler çalışmaz) */}
        <Toaster position="top-right" reverseOrder={false} />

        <LanguageProvider>
          <AuthProvider>
            <CartProvider>
              <ModalProvider>

                {/* PublicLayout: Navbar/Footer'ı yönetir */}
                <PublicLayout settings={settings}>
                  {children}
                </PublicLayout>

                {/* GLOBAL BİLEŞENLER */}
                <AuthModal />    {/* Giriş/Kayıt Modalı */}
                <CartDrawer />   {/* Sepet Çekmecesi */}
                
                {/* 2. CANLI DESTEK WIDGET'I (Burada olmalı) */}
                <ChatWidget />   

              </ModalProvider>
            </CartProvider>
          </AuthProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}