// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext"; // 1. AuthProvider'ı import et

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GaleryBlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>

          {children}

        </AuthProvider>
      </body>
    </html>
  );
}